# https://starship.rs/config/
# Ice Blue Tokyo - „Éê„É©„É≥„ÇπÁ¥´„Ç¢„ÇØ„Çª„É≥„ÉàÔºàTokyo NightÈ¢®Ôºâ

command_timeout = 1000
right_format = """$time"""

[time]
disabled = false
style = "#939594"
format = "[$time]($style)"

[aws]
style = "bg:#66c2ff fg:black"
symbol = "‚òÅ "
format = "[ÓÇ∞](fg:black bg:#66c2ff)[$symbol$profile]($style)[ÓÇ∞](fg:#66c2ff bg:black)"

[character]
success_symbol = "[‚ùØ](#80d4ff)"
error_symbol = "[‚úó](#ff4757)"

[cmd_duration]
style = "#66c2ff"
format = "[ÓÇ∞](fg:black bg:#66c2ff)[Ô®ö$duration](bg:$style fg:black)[ÓÇ∞](fg:$style)"

[directory]
style = "#4db8ff"
truncate_to_repo = false
fish_style_pwd_dir_length = 1
format = "[ÓÇ∞](fg:black bg:#4db8ff)[$path[$read_only](bg:$style fg:black)](bg:$style fg:black)[ÓÇ∞](fg:$style)"
read_only = " ÔÄ£"

[docker_context]
style = "fg:black bg:#7dcfff"
symbol = "üê≥  "
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$context]($style)[ÓÇ∞](fg:#7dcfff)"

[git_branch]
style = "#bb9af7"
format = "[ÓÇ∞](fg:black bg:$style)[ $symbol$branch](fg:black bg:$style)[ÓÇ∞](fg:$style)"

[git_commit]
style = "#bb9af7"
format = "\b[ ](bg:$style)[\\($hash$tag\\)](fg:black bg:$style)[ÓÇ∞](fg:$style)"

[git_state]
style = "#bb9af7"
format = "\b[ ](bg:$style)[ \\($state( $progress_current/$progress_total)\\)](fg:black bg:$style)[ÓÇ∞](fg:$style)"

[git_status]
style = "#bb9af7"
format = "(\b[ ](bg:$style fg:black)$conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind[ÓÇ∞](fg:$style))"
conflicted = "[ÔÅ± ](bold fg:88 bg:#bb9af7)[ ÔëÄ ${count} ](fg:black bg:#bb9af7)"
staged = "[ÔÅß $count ](fg:black bg:#bb9af7)"
modified = "[Ô£™ ${count} ](fg:black bg:#bb9af7)"
renamed = "[ÔÄ´ ${count} ](fg:black bg:#bb9af7)"
deleted = "[ÔÄî ${count} ](fg:black bg:#bb9af7)"
untracked = "[?${count} ](fg:black bg:#bb9af7)"
stashed = "[Ôíá ${count} ](fg:black bg:#bb9af7)"
ahead = "[ÔÉÆ ${count} ](fg:#2d5566 bg:#bb9af7)"
behind = "[ÔÉ≠ ${count} ](fg:black bg:#bb9af7)"
diverged = "[ÔÅ± ](fg:88 bg:#bb9af7)[ Ô≠Ä ](fg:black bg:#bb9af7)[ÔÉÆ ${ahead_count} ](fg:black bg:#bb9af7)[ÔÉ≠ ${behind_count} ](fg:black bg:#bb9af7)"

[golang]
symbol = "Ô≥ë "
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version]($style)[ÓÇ∞](fg:#7dcfff)"

[helm]
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol($version)]($style)[ÓÇ∞](fg:#7dcfff)"

[java]
symbol = "ÔÉ¥ "
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version]($style)[ÓÇ∞](fg:#7dcfff)"

[kotlin]
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version]($style)[ÓÇ∞](fg:#7dcfff)"

[kubernetes]
format = "[ÓÇ∞](fg:white bg:#7856c7)[$symbol$context](fg:white bg:#7856c7)[ÓÇ∞](fg:#7856c7)"
disabled = false

#[memory_usage]
#style = "#66c2ff"
#symbol = "Ôûô "
#format = "[ÓÇ∞](fg:black bg:#66c2ff)[$symbol$ram](bg:$style fg:black)[ÓÇ∞](fg:$style)"
#threshold = 95
#disabled = false

[nodejs]
style = "green"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol($version)](fg:black bg:#7dcfff)[ÓÇ∞](fg:#7dcfff)"

[ocaml]
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version]($style)[ÓÇ∞](fg:#7dcfff)"

[package]
disabled = true

[php]
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version]($style)[ÓÇ∞](fg:#7dcfff)"

[python]
symbol = "Ô†† "
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$pyenv_prefix$version$virtualenv]($style)[ÓÇ∞](fg:#7dcfff)"

[ruby]
symbol = "Óàû "
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version](fg:black bg:#7dcfff)(fg:black bg:#7dcfff)[ÓÇ∞](fg:#7dcfff)"

[rust]
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version]($style)[ÓÇ∞](fg:#7dcfff)"

[scala]
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version]($style)[ÓÇ∞](fg:#7dcfff)"

[swift]
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version]($style)[ÓÇ∞](fg:#7dcfff)"

[shell]
fish_indicator = ""
bash_indicator = "bash "
zsh_indicator = "zsh "
powershell_indicator = ""
format = "[$indicator](fg:#7856c7)"
disabled = false
[shlvl]
symbol = "Ôïù‚Äâ"
style = "fg:white bg:#7856c7"
format = "[ÓÇ∞](fg:white bg:#7856c7)[$symbol$shlvl]($style)[ÓÇ∞](fg:#7856c7)"
disabled = false

[terraform]
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$workspace]($style)[ÓÇ∞](fg:#7dcfff)"

[username]
style_user = "#80d4ff"
style_root = "#C00311"
format = "[ÓÇ∞](fg:black bg:$style)[$user](fg:black bg:$style)[ÓÇ∞](fg:$style)"

[vagrant]
style = "fg:black bg:#7dcfff"
format = "[ÓÇ∞](fg:black bg:#7dcfff)[$symbol$version]($style)[ÓÇ∞](fg:#7dcfff)"
